// Code generated by jtd-codegen for TypeScript v0.2.1

export enum PrintJobMode {
  Err = "ERR",
  Std = "STD",
}

export interface PrintJob {
  mode: PrintJobMode;
  name: string;
  text: string;
}
