// Code generated by jtd-codegen for TypeScript v0.2.1

/**
 * Log level
 */
export enum LogEntryLevel {
  Debug = "DEBUG",
  Err = "ERR",
  Info = "INFO",
  Trace = "TRACE",
  Warn = "WARN",
}

export interface LogEntry {
  /**
   * Log level
   */
  level: LogEntryLevel;

  /**
   * The text to be logged
   */
  text: string;
}
