// Code generated by jtd-codegen for TypeScript v0.2.1

/**
 * The log level to be used by the logger
 */
export enum LogLevel {
  Debug = "DEBUG",
  Err = "ERR",
  Info = "INFO",
  Trace = "TRACE",
  Warn = "WARN",
}
